INSERT INTO AUTOR (NOME) VALUES ('Silvio Santos');
INSERT INTO AUTOR (NOME) VALUES ('Gugu Liberato');

INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE, AUTOR_ID ) VALUES ( 1, 'Use a cabeça Java', 30, 1 );
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE, AUTOR_ID ) VALUES ( 2, 'Java como programar', 50, 1 );
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE, AUTOR_ID ) VALUES ( 3, 'Spring boot', 20, 2 );